# Generated by Django 4.2.4 on 2023-08-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_alter_nairobihealthfacilities_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NairobiHealthFacilities',
            new_name='dogShelter',
        ),
        migrations.RenameModel(
            old_name='NairobiSubCounties',
            new_name='SubCounties',
        ),
    ]
